git:
  depth: 1

os: linux
language: c
dist: trusty
sudo: false

install:
  - cd ${TRAVIS_BUILD_DIR}
  - curl -L "https://github.com/vitasdk/autobuilds/releases/download/master-linux-v844/vitasdk-x86_64-linux-gnu-2018-08-09_08-23-44.tar.bz2" | tar xj
  - for name in libvita2d libpng zlib; do curl -L "http://dl.vitasdk.org/${name}.tar.xz" | tar -xJC vitasdk/arm-vita-eabi; done

script:
  - export VITASDK=${TRAVIS_BUILD_DIR}/vitasdk
  - export PATH=${VITASDK}/bin:${PATH}
  - cd hello_cpp_world
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
