git:
  depth: 1

os: linux
language: c
dist: trusty
sudo: required

install:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/vitasdk/vdpm
  - cd vdpm
  - ./bootstrap-vitasdk.sh
  - ./install-all.sh
  
script:
  - export VITASDK=/usr/local/vitasdk
  - export PATH=${VITASDK}/bin:${PATH}
  - cd hello_cpp_world
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
